version: '3.8'

# networks:
#   my_network:
#     driver: bridge

services:
  # web:
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:5000
  #     - ASPNETCORE_Kestrel__Certificates__Default__Password=password
  #     - ASPNETCORE_Kestrel__Certificates__Default__Path=/.aspnet/https/aspnetapp.pfx
  #     - DB_CONNECTION_STRING=Server=db;Port=5432;Database=orders_service;User Id=root;Password=root;
  #   depends_on:
  #     - db
  #   networks:
  #     - my_network

  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: orders_service
    ports:
      - "5432:5432"
    volumes:
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - pg_data:/var/lib/postgresql/data/
    # networks:
    #   - my_network

volumes:
  pg_data: